CREATE DATABASE IF NOT EXISTS pepe_house;

USE pepe_house;

DROP TABLE if EXISTS pcons;

CREATE TABLE pcons (
	 id 			BIGINT(20) UNSIGNED  PRIMARY KEY 		  AUTO_INCREMENT
	,name			VARCHAR(20)				NOT NULL
	,created_at TIMESTAMP 				NOT NULL 	DEFAULT CURRENT_TIMESTAMP()
	,updated_at TIMESTAMP 				NOT NULL 	DEFAULT CURRENT_TIMESTAMP()
	,deleted_at TIMESTAMP 				NULL
);
