DROP TABLE if EXISTS boards;

CREATE TABLE boards (
	 id 			BIGINT(20) UNSIGNED	PRIMARY KEY 		  AUTO_INCREMENT
	,tab_id		BIGINT(20) UNSIGNED	NOT NULL 	DEFAULT 0 
	,pcon_id		BIGINT(20) UNSIGNED	NOT NULL 	DEFAULT 0 
	,title 		VARCHAR(50) 			NOT NULL
	,content 	VARCHAR(2000) 			NOT NULL
	,view			BIGINT(20)				NOT NULL		DEFAULT 0
	,bookmark	VARCHAR(1)				NOT NULL		DEFAULT 0
	,notice		VARCHAR(1)				NOT NULL		DEFAULT 0
	,created_at TIMESTAMP 				NOT NULL 	DEFAULT CURRENT_TIMESTAMP()
	,updated_at TIMESTAMP 				NOT NULL 	DEFAULT CURRENT_TIMESTAMP()
	,deleted_at TIMESTAMP 				NULL
	,CONSTRAINT fk_boards_tab_id FOREIGN KEY (tab_id) REFERENCES board_tabs (id)
	,CONSTRAINT fk_boards_pcon_id FOREIGN KEY (pcon_id) REFERENCES pcons (id)
);