DROP TABLE if EXISTS board_tabs;

CREATE TABLE board_tabs (
	 id 			BIGINT(20) UNSIGNED	PRIMARY KEY 		  AUTO_INCREMENT
	,number 		VARCHAR(20) 			NOT NULL
	,name 		VARCHAR(50) 			NOT NULL
	,created_at TIMESTAMP 				NOT NULL 	DEFAULT CURRENT_TIMESTAMP()
	,updated_at TIMESTAMP 				NOT NULL 	DEFAULT CURRENT_TIMESTAMP()
	,deleted_at TIMESTAMP 				NULL
);